from __future__ import annotations

from datetime import datetime
from html import escape
from pathlib import Path
from typing import List

import markdown

from .fetch import NewsItem


def fallback_report(items: List[NewsItem], report_date: str, error: Exception) -> str:
    lines = [
        f"# AI / Agent 前沿资讯日报 - {report_date}",
        "",
        "## 生成状态",
        "",
        f"LiteLLM 总结失败：`{error}`",
        "",
        "下面是已抓取并过滤后的候选资讯，方便排查或手动阅读。",
        "",
        "## 候选来源",
        "",
    ]
    for item in items:
        published = item.published_at.isoformat() if item.published_at else "unknown"
        lines.extend(
            [
                f"- [{item.title}]({item.url})",
                f"  - 来源：{item.source}",
                f"  - 发布时间：{published}",
                f"  - 摘要：{item.summary[:300]}",
            ]
        )
    return "\n".join(lines).strip() + "\n"


def render_html(markdown_content: str, report_date: str, generated_at: str) -> str:
    body = markdown.markdown(
        markdown_content,
        extensions=["extra", "sane_lists", "smarty", "mdx_linkify"],
        output_format="html5",
    )
    title = f"AI / Agent 前沿资讯日报 - {report_date}"
    return f"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{escape(title)}</title>
  <style>
    :root {{
      color-scheme: light;
      --bg: #f7f7f4;
      --paper: #ffffff;
      --text: #202124;
      --muted: #626b75;
      --line: #e3e1dc;
      --accent: #166534;
      --accent-bg: #ecfdf3;
      --code-bg: #f3f4f6;
    }}
    * {{ box-sizing: border-box; }}
    body {{
      margin: 0;
      background: var(--bg);
      color: var(--text);
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif;
      line-height: 1.72;
    }}
    main {{
      width: min(920px, calc(100% - 32px));
      margin: 32px auto;
      background: var(--paper);
      border: 1px solid var(--line);
      border-radius: 8px;
      padding: 40px 48px;
      box-shadow: 0 10px 30px rgba(18, 24, 31, 0.06);
    }}
    .meta {{
      margin: 0 0 28px;
      color: var(--muted);
      font-size: 14px;
    }}
    h1 {{
      margin: 0 0 10px;
      font-size: clamp(28px, 4vw, 42px);
      line-height: 1.2;
      letter-spacing: 0;
    }}
    h2 {{
      margin: 36px 0 14px;
      padding-top: 18px;
      border-top: 1px solid var(--line);
      font-size: 22px;
      letter-spacing: 0;
    }}
    ul, ol {{ padding-left: 1.35rem; }}
    li {{ margin: 10px 0; }}
    a {{
      color: var(--accent);
      text-decoration-thickness: 1px;
      text-underline-offset: 3px;
      overflow-wrap: anywhere;
    }}
    strong {{ color: #111827; }}
    code {{
      background: var(--code-bg);
      border-radius: 4px;
      padding: 0.12rem 0.28rem;
      font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
      font-size: 0.92em;
    }}
    blockquote {{
      margin: 18px 0;
      padding: 12px 16px;
      background: var(--accent-bg);
      border-left: 4px solid var(--accent);
    }}
    .footer {{
      margin-top: 36px;
      padding-top: 16px;
      border-top: 1px solid var(--line);
      color: var(--muted);
      font-size: 13px;
    }}
    @media (max-width: 640px) {{
      main {{
        width: 100%;
        margin: 0;
        border: 0;
        border-radius: 0;
        padding: 24px 18px;
      }}
    }}
  </style>
</head>
<body>
  <main>
    <div class="meta">生成时间：{escape(generated_at)}</div>
    {body}
    <div class="footer">Generated by local AI news agent.</div>
  </main>
</body>
</html>
"""


def write_report(report_dir: Path, report_date: str, content: str) -> Path:
    report_dir.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now().isoformat(timespec="seconds")
    markdown_path = report_dir / f"{report_date}.md"
    markdown_path.write_text(f"{content.rstrip()}\n\n<!-- generated_at: {stamp} -->\n", encoding="utf-8")

    path = report_dir / f"{report_date}.html"
    path.write_text(render_html(content, report_date, stamp), encoding="utf-8")
    return path
